kind: pipeline
name: epicurus

type: docker
steps:
  - name: test
    image: node:14.4.0-alpine
    commands:
      - npm install
      - npm test
  # - name: publish to npm
  #   image: plugins/npm
  #   settings:
  #     secrets: [npm_username, npm_password, npm_email]
